name: RSLB
version: '${version}'
main: com.rserene.chosen.server.RSLB
author: Chosen_1st
website: www.RSerene.com
api-version: '26.2'
folia-supported: true
load: POSTWORLD
commands:
  rslb:
    aliases: [rsl]
    description: "RSLB - 正版与 LittleSkin 登录"
    permission: RSLB.base
permissions:
  RSLB.base:
    description: "RSLB base command"
    default: true
  RSLB.tab.complete:
    description: "RSLB tab complete"
    default: true
  RSLB.reload:
    description: "RSLB reload"
    default: op
  RSLB.confirm:
    description: "RSLB confirm"
    default: true
  RSLB.erase.username:
    description: "RSLB erase username"
    default: op
  RSLB.erase.all:
    description: "RSLB erase all usernames"
    default: op
  RSLB.whitelist.add:
    description: "RSLB whitelist add"
    default: op
  RSLB.whitelist.remove:
    description: "RSLB whitelist remove"
    default: op
  RSLB.whitelist.specific.add:
    description: "RSLB whitelist specific add"
    default: op
  RSLB.whitelist.specific.remove:
    description: "RSLB whitelist specific remove"
    default: op
  RSLB.whitelist.list:
    description: "RSLB whitelist list"
    default: op
  RSLB.whitelist.list.verbose:
    description: "RSLB whitelist list verbose"
    default: op
  RSLB.rename.oneself:
    description: "RSLB rename oneself"
    default: op
  RSLB.rename.other:
    description: "RSLB rename other"
    default: op
  RSLB.info.oneself:
    description: "RSLB info oneself"
    default: op
  RSLB.info.other:
    description: "RSLB info other"
    default: op
  RSLB.profile.create:
    description: "RSLB profile create"
    default: op
  RSLB.profile.set.oneself:
    description: "RSLB profile set oneself"
    default: op
  RSLB.profile.set.other:
    description: "RSLB profile set other"
    default: op
  RSLB.profile.remove:
    description: "RSLB profile remove"
    default: op
  RSLB.list:
    description: "RSLB list"
    default: op
  RSLB.find.online:
    description: "RSLB find online"
    default: op
  RSLB.find.profile:
    description: "RSLB find profile"
    default: op
  RSLB.link.to:
    description: "RSLB link to"
    default: true
  RSLB.link.accept:
    description: "RSLB link accept"
    default: true
  RSLB.link.code:
    description: "RSLB link code"
    default: true
